// 데모/테스트용 목(mock) 데이터

export const DEMO_GROUP_BUY = {
  id: 'demo-gb-001',
  title: '3월 4주차 반찬·신선식품 공구',
  description: '이번 주 신선한 제철 채소와 반찬류를 모아봤어요 🥬',
  status: 'active',
  open_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  close_at: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
  delivery_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const DEMO_PRODUCTS = [
  { id: 'demo-p-001', group_buy_id: 'demo-gb-001', name: '국내산 시금치 500g', price: 4500, unit: '봉', stock_quantity: 30, is_available: true, image_url: null, description: '산지직송 국내산', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-002', group_buy_id: 'demo-gb-001', name: '무농약 당근 1kg', price: 3800, unit: 'kg', stock_quantity: 20, is_available: true, image_url: null, description: '당도 높은 제주 당근', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-003', group_buy_id: 'demo-gb-001', name: '조기 굴비 10마리', price: 18000, unit: '묶음', stock_quantity: 15, is_available: true, image_url: null, description: '영광 법성포 굴비', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-004', group_buy_id: 'demo-gb-001', name: '한우 국거리 400g', price: 22000, unit: '팩', stock_quantity: 10, is_available: true, image_url: null, description: '1++ 한우 사골 국거리', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-005', group_buy_id: 'demo-gb-001', name: '제철 딸기 500g', price: 8500, unit: '팩', stock_quantity: 25, is_available: true, image_url: null, description: '논산 설향 딸기', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-006', group_buy_id: 'demo-gb-001', name: '유정란 30구', price: 9800, unit: '판', stock_quantity: 20, is_available: false, image_url: null, description: '완판 임박!', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-007', group_buy_id: 'demo-gb-001', name: '[미식연구소] 젓가락돈까스 500g', price: 12900, unit: '팩', stock_quantity: 15, is_available: true, image_url: null, description: '바삭한 수제 돈까스', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-008', group_buy_id: 'demo-gb-001', name: '[후쿠오카함바그] 함박 스테이크 400g', price: 12900, unit: '팩', stock_quantity: 15, is_available: true, image_url: null, description: '함박150gX2 + 소스50gX2', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-009', group_buy_id: 'demo-gb-001', name: '[서문시장] 왕 땅콩빵 300g', price: 10900, unit: '봉', stock_quantity: 20, is_available: true, image_url: null, description: '28개 내외 땅콩 가득 빵', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'demo-p-010', group_buy_id: 'demo-gb-001', name: '[푸드령] 두바이 쫀득 쿠키 65g', price: 5900, unit: '봉', stock_quantity: 30, is_available: true, image_url: null, description: '쫄깃쫄깃 두바이 스타일 쿠키', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
]

export const DEMO_ORDERS = [
  {
    id: 'demo-o-001',
    order_number: 'CS-20240322-001',
    group_buy_id: 'demo-gb-001',
    customer_id: 'demo-customer-001',
    kakao_nickname: '김평창',
    delivery_address: '서울 종로구 평창동 123-45 현대빌라 201호',
    delivery_memo: '문 앞에 놓아주세요',
    total_amount: 35800,
    status: 'pending',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    approved_at: null,
    rejected_reason: null,
    owner_memo: null,
    items: [
      { id: 'demo-oi-001', order_id: 'demo-o-001', product_id: 'demo-p-001', product_name: '국내산 시금치 500g', unit_price: 4500, quantity: 2, subtotal: 9000 },
      { id: 'demo-oi-002', order_id: 'demo-o-001', product_id: 'demo-p-004', product_name: '한우 국거리 400g', unit_price: 22000, quantity: 1, subtotal: 22000 },
      { id: 'demo-oi-003', order_id: 'demo-o-001', product_id: 'demo-p-002', product_name: '무농약 당근 1kg', unit_price: 3800, quantity: 1, subtotal: 3800 },
    ],
    customer: { id: 'demo-customer-001', nickname: '김평창', device_uuid: 'demo-uuid-customer', phone: '010-1234-5678' },
    status_logs: [],
  },
  {
    id: 'demo-o-002',
    order_number: 'CS-20240322-002',
    group_buy_id: 'demo-gb-001',
    customer_id: 'demo-customer-002',
    kakao_nickname: '이부암',
    delivery_address: '서울 종로구 부암동 45-2 그린빌 301호',
    delivery_memo: null,
    total_amount: 26500,
    status: 'paid',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    rejected_reason: null,
    owner_memo: '단골 고객',
    items: [
      { id: 'demo-oi-004', order_id: 'demo-o-002', product_id: 'demo-p-003', product_name: '조기 굴비 10마리', unit_price: 18000, quantity: 1, subtotal: 18000 },
      { id: 'demo-oi-005', order_id: 'demo-o-002', product_id: 'demo-p-005', product_name: '제철 딸기 500g', unit_price: 8500, quantity: 1, subtotal: 8500 },
    ],
    customer: { id: 'demo-customer-002', nickname: '이부암', device_uuid: 'demo-uuid-c2', phone: '010-9876-5432' },
    status_logs: [],
  },
  {
    id: 'demo-o-003',
    order_number: 'CS-20240322-003',
    group_buy_id: 'demo-gb-001',
    customer_id: 'demo-customer-003',
    kakao_nickname: '박홍지',
    delivery_address: '서울 종로구 홍지동 88 코사마트 빌라 102호',
    delivery_memo: '경비실 맡겨주세요',
    total_amount: 18000,
    status: 'delivering',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    rejected_reason: null,
    owner_memo: null,
    items: [
      { id: 'demo-oi-006', order_id: 'demo-o-003', product_id: 'demo-p-003', product_name: '조기 굴비 10마리', unit_price: 18000, quantity: 1, subtotal: 18000 },
    ],
    customer: { id: 'demo-customer-003', nickname: '박홍지', device_uuid: 'demo-uuid-c3', phone: '010-5555-7777' },
    status_logs: [],
  },
  {
    id: 'demo-o-004',
    order_number: 'CS-20240321-015',
    group_buy_id: 'demo-gb-001',
    customer_id: 'demo-customer-004',
    kakao_nickname: '최세검',
    delivery_address: '서울 종로구 세검정로 210 현대아파트 505호',
    delivery_memo: null,
    total_amount: 8500,
    status: 'delivered',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    rejected_reason: null,
    owner_memo: null,
    items: [
      { id: 'demo-oi-007', order_id: 'demo-o-004', product_id: 'demo-p-005', product_name: '제철 딸기 500g', unit_price: 8500, quantity: 1, subtotal: 8500 },
    ],
    customer: { id: 'demo-customer-004', nickname: '최세검', device_uuid: 'demo-uuid-c4', phone: '010-2222-3333' },
    status_logs: [],
  },
  // 상점가 주��� (중앙슈퍼)
  {
    id: 'demo-o-005',
    order_number: 'CS-20240322-005',
    group_buy_id: null,
    store_id: 'central-super',
    store_name: '중앙슈퍼',
    customer_id: 'demo-customer-001',
    kakao_nickname: '김평창',
    delivery_address: '서울 종로구 평창동 123-45 현대빌라 201호',
    delivery_memo: '09:00~12:00',
    total_amount: 17000,
    status: 'pending',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    approved_at: null,
    rejected_reason: null,
    owner_memo: '[상점가] 중앙슈퍼',
    items: [
      { id: 'demo-oi-010', order_id: 'demo-o-005', product_id: 'cs-1', product_name: '국내산 계란 30구', unit_price: 9800, quantity: 1, subtotal: 9800 },
      { id: 'demo-oi-011', order_id: 'demo-o-005', product_id: 'cs-6', product_name: '라면 5개입', unit_price: 4200, quantity: 1, subtotal: 4200 },
      { id: 'demo-oi-012', order_id: 'demo-o-005', product_id: 'cs-2', product_name: '우유 1L', unit_price: 2800, quantity: 1, subtotal: 2800 },
    ],
    customer: { id: 'demo-customer-001', nickname: '김평창', device_uuid: 'demo-uuid-customer', phone: '010-1234-5678' },
    status_logs: [],
  },
  {
    id: 'demo-o-006',
    order_number: 'CS-20240322-006',
    group_buy_id: null,
    store_id: 'central-super',
    store_name: '중앙슈퍼',
    customer_id: 'demo-customer-003',
    kakao_nickname: '박홍지',
    delivery_address: '서울 종로구 홍지동 88 코사마트 빌라 102호',
    delivery_memo: '12:00~15:00 / 초인종 금지',
    total_amount: 26600,
    status: 'paid',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    approved_at: null,
    rejected_reason: null,
    owner_memo: '[상점가] 중앙슈퍼',
    items: [
      { id: 'demo-oi-013', order_id: 'demo-o-006', product_id: 'cs-7', product_name: '휴지 30롤', unit_price: 12900, quantity: 1, subtotal: 12900 },
      { id: 'demo-oi-014', order_id: 'demo-o-006', product_id: 'cs-4', product_name: '참기름 320ml', unit_price: 8900, quantity: 1, subtotal: 8900 },
      { id: 'demo-oi-015', order_id: 'demo-o-006', product_id: 'cs-3', product_name: '두부 (국산콩)', unit_price: 2500, quantity: 2, subtotal: 5000 },
    ],
    customer: { id: 'demo-customer-003', nickname: '박홍지', device_uuid: 'demo-uuid-c3', phone: '010-5555-7777' },
    status_logs: [],
  },
]

export const DEMO_DELIVERIES = [
  {
    id: 'demo-d-003',
    order_id: 'demo-o-001',
    driver_id: null,
    status: 'pending',
    assigned_at: null,
    picked_up_at: null,
    delivered_at: null,
    failed_reason: null,
    driver_memo: null,
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    order: {
      id: 'demo-o-001',
      order_number: 'CS-20240322-001',
      status: 'approved',
      kakao_nickname: '김평창',
      delivery_address: '서울 종로구 평창동 123 코사마트 아파트 201호',
      delivery_memo: '현관 비밀번호 1234*',
      total_amount: 45800,
      items: [
        { product_name: '국내산 계란 30구' },
        { product_name: '참기름 320ml' },
      ],
      customer: { phone: '010-1234-5678' },
    },
    driver: null,
  },
  {
    id: 'demo-d-001',
    order_id: 'demo-o-002',
    driver_id: 'demo-driver-001',
    status: 'assigned',
    assigned_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    picked_up_at: null,
    delivered_at: null,
    failed_reason: null,
    driver_memo: null,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    order: {
      id: 'demo-o-002',
      order_number: 'CS-20240322-002',
      kakao_nickname: '이부암',
      delivery_address: '서울 종로구 부암동 45-2 그린빌 301호',
      delivery_memo: null,
      total_amount: 26500,
      items: [
        { product_name: '조기 굴비 10마리' },
        { product_name: '제철 딸기 500g' },
      ],
      customer: { phone: '010-9876-5432' },
    },
    driver: { id: 'demo-driver-001', nickname: '배달기사', device_uuid: 'demo-uuid-driver' },
  },
  {
    id: 'demo-d-002',
    order_id: 'demo-o-003',
    driver_id: 'demo-driver-001',
    status: 'picked_up',
    assigned_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    picked_up_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    delivered_at: null,
    failed_reason: null,
    driver_memo: null,
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    order: {
      id: 'demo-o-003',
      order_number: 'CS-20240322-003',
      kakao_nickname: '박홍지',
      delivery_address: '서울 종로구 홍지동 88 코사마트 빌라 102호',
      delivery_memo: '경비실 맡겨주세요',
      total_amount: 18000,
      items: [
        { product_name: '조기 굴비 10마리' },
      ],
      customer: { phone: '010-5555-7777' },
    },
    driver: { id: 'demo-driver-001', nickname: '배달기사', device_uuid: 'demo-uuid-driver' },
  },
]

export const DEMO_STATS = {
  todayOrders: 2,
  pendingCount: 1,
  paidCount: 1,
  deliveringCount: 2,
  todayRevenue: 88800,
}
